---
- name: create group
  hosts: db
  tasks:
  - name: using group module
    group:
      name: jyp
      state: present
      gid: 2300

  - name: using user module
    ansible.builtin.user:
      name: jyp
      uid: 2300
      group: jyp
